name: matule_me_speedrun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^9.3.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  flutter_otp_text_field: ^1.4.0+2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/poppins/Raleway-v4020-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Raleway-v4020-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Raleway-v4020-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Raleway-v4020-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Raleway-v4020-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Raleway-v4020-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Raleway-v4020-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Raleway-v4020-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Raleway-v4020-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Raleway-v4020-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Raleway-v4020-ThinItalic.ttf
          weight: 100
          style: italic

flutter_native_splash:
  color: "#48B2E7"
  image: "assets/icons/splash.png"