name: matule_me_speedrun
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  auto_route: ^10.0.1
  barcode_widget: ^2.0.4
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.5
  flutter_otp_text_field: ^1.5.1+1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-v4020-Black.otf
          weight: 900
        - asset: assets/fonts/raleway/Raleway-v4020-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-v4020-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-Bold.otf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-v4020-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-SemiBold.otf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-v4020-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-Medium.otf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-v4020-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-Regular.otf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-v4020-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-Light.otf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-v4020-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-v4020-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-v4020-Thin.otf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-v4020-ThinItalic.otf
          weight: 100
          style: italic

flutter_native_splash:
  color: "#48B2E7"
  image: "assets/icons/splash.png"